import bcrypt from 'bcryptjs';

const data = {
    user: [
        {
            name:'Non',
            email: 'admin@example.com',
            password: bcrypt.hashSync('1234', 8),
            isAdmin: true,
        },
        {
            name:'John',
            email: 'user@example.com',
            password: bcrypt.hashSync('1234', 8),
            isAdmin: false,
        },
    ],
    products:[
        {
            name:'Rapunzel',
            price:15.00,
            nickname:'Devils\' Ivy; Epipremnum aureum; Ceylon creeper; Golden Pothos',
            botanical_name:'Devil\'s ivy',
            category:'Hanging and Climbing',
            count_in_stock:20,
            description:'She is the perfect houseplant. She’ll live in almost any light conditions and looks spectacular.',
            image_url:'None',
            image_file:'/images/p1.jpg',
        },
        {
            name:'Venus',
            price:10.00,
            nickname:'Adiantum; Venus\' hair fern',
            botanical_name:'Maidenhair fern',
            category:'Ferns',
            count_in_stock:16,
            description:'-None-',
            image_url:'None',
            image_file:'/images/p2.jpg',
        },
        {
            name:'Sarah',
            price:35.00,
            nickname:'Pot Belly Fig; Laurel Fig; Laurel Rubber; Curtain Fig; Strangling Fig; Ceylon creeper; Golden Pothos',
            botanical_name:'Ficus microcarpa moclame',
            category:'Palms and trees',
            count_in_stock:16,
            description:'-None-',
            image_url:'None',
            image_file:'/images/p3.jpg',
        },
        {
            name:'Marcel',
            price:22.00,
            nickname:'-None-',
            botanical_name:'Asparagus \'Meyeri\'',
            category:'Ferns',
            count_in_stock:20,
            description:'Marcel stars in our RHS Chelsea Flower Show exhibit, the \'Pharmacy of House Plants\'. He\'s a limited edition, so you’ll have to be quick.',
            image_url:'None',
            image_file:'/images/p4.jpg',
        },
        {
            name:'Fleur',
            price:20.00,
            nickname:'Tail flower; Flamingo flower; Laceleaf; Anthurium Andraeanum',
            botanical_name:'Anthurium',
            category:'Flowering',
            count_in_stock:11,
            description:'-None-',
            image_url:'None',
            image_file:'/images/p5.jpg',
        },
        {
            name:'Sharon',
            price:7.50,
            nickname:'Chamaedorea elegans; Neanthe bella palm; Parlour palm',
            botanical_name:'Parlour Palm',
            category:'Palms and trees',
            count_in_stock:17,
            description:'-None-',
            image_url:'None',
            image_file:'/images/p6.jpg',
        },
    ]
};
export default data;